export const adminLayoutClasses = {
  page: "min-h-screen bg-[#07060d] text-white",
  shell: "flex min-h-screen w-full flex-col lg:flex-row",
  sidebar: "flex w-full shrink-0 flex-col border-b border-violet-500/15 bg-[#0d0b18] px-6 py-6 lg:w-[280px] lg:border-b-0 lg:border-r lg:px-8 lg:py-9",
  sidebarTitle: "text-sm font-semibold text-violet-400",
  sidebarNav: "grid gap-1 sm:grid-cols-2 lg:block lg:space-y-1",
  navLink: "flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition",
  navLinkActive: "bg-violet-500/15 text-violet-300",
  navLinkInactive: "text-slate-500 hover:bg-white/5 hover:text-white",
  content: "min-w-0 flex-1 bg-[#07060d] px-5 py-8 md:px-10 md:py-10",
  pageHeader: "mb-6 flex flex-wrap items-center justify-between gap-4",
  pageTitle: "text-2xl font-semibold uppercase tracking-tight text-white md:text-3xl",
  panel: "rounded-2xl border border-violet-500/20 bg-[#121020] px-6 py-6 md:px-8 md:py-8",
  table: "w-full text-left text-sm",
  tableHead: "border-b border-violet-500/20 text-slate-500",
  tableRow: "border-b border-violet-500/10 last:border-b-0",
  actionButton: "inline-flex items-center justify-center rounded-xl border border-violet-500/25 bg-transparent px-4 py-2 text-sm font-semibold text-violet-300 transition hover:bg-violet-500/10",
  primaryButton: "inline-flex items-center justify-center rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-500",
  dangerButton: "inline-flex items-center justify-center rounded-xl border border-red-500/30 bg-transparent px-4 py-2 text-sm font-semibold text-red-400 transition hover:bg-red-500/10",
  emptyState: "py-12 text-center text-sm text-slate-500",
  badge: "inline-flex rounded-full bg-violet-500/15 px-3 py-1 text-xs font-semibold text-violet-300",
};
