export const adminNotificationsPageClasses = {
  page: "mx-auto w-full max-w-[920px]",
  header: "flex flex-wrap items-center justify-between gap-6 border-b border-violet-500/15 pb-8",
  title: "text-[28px] font-semibold uppercase leading-tight tracking-tight text-white",
  markAllButton: "text-sm font-semibold text-violet-300 underline underline-offset-4 transition hover:text-violet-200 disabled:text-slate-600",
  list: "divide-y divide-violet-500/15",
  item: "flex gap-4 py-6 first:pt-8",
  avatar: "grid size-11 shrink-0 place-items-center rounded-full text-xs font-semibold",
  content: "min-w-0 flex-1",
  summary: "text-sm leading-6 text-slate-300",
  userName: "font-semibold text-white",
  articleTitle: "font-medium text-slate-300",
  quote: "mt-3 text-sm leading-6 text-slate-500",
  timestamp: "mt-3 text-sm font-medium text-violet-400",
  viewLink: "shrink-0 self-start text-sm font-semibold text-violet-300 underline underline-offset-4 transition hover:text-violet-200",
  emptyState: "py-16 text-center text-sm text-slate-500",
};
