export const adminArticleFormPageClasses = {
  page: "mx-auto w-full max-w-[920px]",
  header: "mb-10 flex flex-wrap items-center justify-between gap-6 border-b border-transparent",
  title: "text-[28px] font-semibold uppercase leading-tight tracking-tight text-white",
  headerActions: "flex items-center gap-4",
  outlineButton: "inline-flex h-10 items-center justify-center rounded-xl border border-violet-500/30 px-5 text-sm font-semibold text-violet-300 transition hover:bg-violet-500/10",
  primaryButton: "inline-flex h-10 items-center justify-center rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white transition hover:bg-violet-500",
  form: "space-y-6",
  fieldGroup: "space-y-2",
  narrowField: "w-full max-w-[358px]",
  fullField: "w-full",
  label: "block text-sm font-medium text-slate-400",
  input: "h-11 w-full rounded-xl border-violet-500/20 bg-[#0b0913] px-4 text-sm text-white shadow-none placeholder:text-slate-600 focus-visible:ring-violet-500/30",
  authorInput: "h-11 w-full rounded-xl border-violet-500/10 bg-[#121020] px-4 text-sm text-slate-500 shadow-none",
  textarea: "w-full resize-y rounded-xl border border-violet-500/20 bg-[#0b0913] px-4 py-3 text-sm text-white shadow-none outline-none placeholder:text-slate-600 focus-visible:ring-2 focus-visible:ring-violet-500/30",
  introTextarea: "min-h-[96px]",
  contentTextarea: "min-h-[520px]",
  errorText: "text-xs font-medium text-red-400",
  thumbnailRow: "flex flex-wrap items-end gap-6",
  thumbnailPreview: "grid h-[200px] w-[358px] shrink-0 place-items-center overflow-hidden rounded-xl border border-violet-500/20 bg-[#121020]",
  thumbnailImage: "size-full object-cover",
  thumbnailPlaceholder: "text-slate-500",
  deleteButton: "mt-2 inline-flex items-center gap-2 text-sm font-semibold text-red-400 transition hover:text-red-300",
};
