export const pageClasses = {
  heroWrapper: "relative -mx-5 overflow-hidden bg-violet-950/20 md:mx-0 md:rounded-2xl",
  heroImage: "h-[280px] w-full object-cover opacity-85 md:h-[520px]",
  articleMeta: "mt-8 flex flex-wrap items-center gap-3 text-xs font-medium text-slate-500",
  title: "mt-5 text-3xl font-semibold leading-tight tracking-tight text-white md:text-5xl",
  intro: "mt-5 text-base leading-8 text-slate-400 md:text-lg",
  sectionHeading: "mt-10 text-xl font-semibold leading-tight text-white md:text-2xl",
  paragraph: "mt-4 text-base leading-8 text-slate-400",
  shareBar: "mt-10 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-violet-500/20 bg-[#121020] px-4 py-3 md:px-5 md:py-4",
  likeBtn: "flex items-center gap-2 rounded-xl border border-violet-500/25 px-5 py-2.5 text-sm font-semibold text-slate-300 transition hover:bg-violet-500/10",
  shareActions: "flex items-center gap-3",
  copyBtn: "flex items-center gap-2 rounded-xl border border-violet-500/25 px-4 py-2.5 text-sm font-semibold text-slate-300 transition hover:bg-violet-500/10",
  socialBtn: "grid size-10 place-items-center rounded-xl text-base font-semibold text-white transition hover:brightness-110",
  commentInput: "mt-3 w-full rounded-xl border border-violet-500/20 bg-[#0b0913] px-4 py-3 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-violet-500/30",
  sendBtn: "mt-3 rounded-xl bg-violet-600 px-6 py-2.5 text-sm font-medium text-white transition hover:bg-violet-500",
  commentAvatar: "grid size-8 shrink-0 place-items-center rounded-full text-[11px] font-semibold",
  authorCard: "rounded-2xl border border-violet-500/20 bg-[#121020] p-5 md:p-6 lg:sticky lg:top-24",
  modalOverlay: "fixed inset-0 z-50 grid place-items-center bg-black/70 px-5",
  modalPanel: "relative w-full max-w-md rounded-2xl border border-violet-500/20 bg-[#121020] px-8 py-12 text-center shadow-xl",
  modalClose: "absolute right-5 top-4 text-2xl leading-none text-slate-500 transition hover:text-white",
  modalTitle: "mx-auto max-w-xs text-3xl font-semibold leading-tight tracking-tight text-white",
  modalPrimary: "mt-8 inline-flex rounded-xl bg-violet-600 px-9 py-3 text-sm font-medium text-white transition hover:bg-violet-500",
  modalFooter: "mt-8 flex items-center justify-center gap-2 text-sm text-slate-500",
  modalLogin: "font-semibold text-violet-300 underline underline-offset-4 hover:text-violet-200",
};
